#!/bin/bash
#USE-Flag build tests for job @@JOB@@

export TATT_TEST_TYPE="use"
export TATT_REPORTFILE="@@REPORTFILE@@"
export TATT_BUILDLOGDIR="@@BUILDLOGDIR@@"
export TATT_EMERGEOPTS="@@EMERGEOPTS@@"

source "@@TEMPLATEDIR@@tatt_functions.sh"

echo '# bug: @@BUG@@' > @@REPORTFILE@@
echo "# time: $(date -u +"%Y-%m-%d %H:%M:%S")" >> @@REPORTFILE@@

test_ret=0
